name: PR Comments

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:

  Check-Changed-Files-Docstrings:
    name: Check Docstrings For Changed Files On PR
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - uses: iterative/setup-cml@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install Pre-Commit
      env:
        PIP_EXTRA_INDEX_URL: https://pypi-proxy.saltstack.net/root/local/+simple/
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        #pre-commit install --install-hooks

    - id: changed-files
      name: Get Changed Files
      uses: dorny/paths-filter@v2
      with:
        token: ${{ github.token }}
        list-files: json
        filters: |
          repo:
            - added|modified:
              - '**'
          deleted:
            - deleted:
              - '**'
          salt:
            - added|modified:
              - 'salt/**'

    - name: Check Docstrings For Changed Files On PR
      id: check-known-missing-docstrings
      if: github.event_name == 'pull_request' && steps.changed-files.outputs.salt == 'true'
      continue-on-error: true
      run: |
        pre-commit run -v --hook-stage manual check-known-missing-docstrings --show-diff-on-failure --color=always --files ${{ join(fromJSON(steps.changed-files.outputs.salt_files), ' ') }}

    - name: Comment on PR
      if: steps.check-known-missing-docstrings.outcome == 'failure'
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "## The Salt Project could use **Your** help" > comment.md
        echo >> comment.md
        echo "<details>" >> comment.md
        echo "<summary>Please check the following and see if you can help.</summary>" >> comment.md
        echo "<pre>${{ steps.check-known-missing-docstrings.output }}</pre>" >> comment.md
        echo "</details>" >> comment.md
        cml-send-comment comment.md
